apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: nginx-demo
  name: nginx-demo
spec:
  ingressClassName: kong
  rules:
  - host: nginx-demo.poc.workisboring.com
    http:
      paths:
      - backend:
          service:
            name: nginx
            port:
              number: 80
        path: /
        pathType: Prefix