apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc-rwo
  annotations:
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: longhorn