apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-configmap
data:
  index.html: |
    <html>
    <h1>Welcome</h1>
    </br>
    <h1>Hi! This is a configmap Index file </h1>
    </html
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-pvc
  name: nginx-pvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-pvc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-pvc
    spec:
      containers:
      - image: nginx:1.20
        imagePullPolicy: IfNotPresent
        name: nginx
        resources:
          limits:
            memory: "100Mi"
            cpu: "100m"
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: data
        - mountPath: /usr/share/nginx/html/
          name: nginx-index-file
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: nginx-pvc-rwo
      - name: nginx-index-file
        configMap:
          name: index-html-configmap
          items:
            - key: index.html
              path: index.html
