apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: echo-pvc
  annotations:
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: loonghorns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: echo
  name: echo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echo
      teir: echoserver
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: echo
        teir: echoserver
    spec:
      containers:
      - image: gcr.io/kubernetes-e2e-test-images/echoserver:2.1
        imagePullPolicy: IfNotPresent
        name: echoserver
        resources:
          limits:
            memory: "100Mi"
            cpu: "100m"
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: echo
---
apiVersion: v1
kind: Service
metadata:
  name: echo-svc
  labels:
    app: echo-svc
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: web
  selector:
    app: echo
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo
spec:
  ingressClassName: nginx
  rules:
  - host: issy-echo.training.dnsfor.me  ## Change to YOUR NAME
    http:
      paths:
      - backend:
          service:
            name: echo-svc
            port:
              number: 80
        path: /
        pathType: Prefix
